apiVersion: v1
kind: Service
metadata:
  name: paymentorder-service
spec:
  selector:
    app: paymentorder
  type: NodePort
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 4006
    nodePort: 31111